allowBuilds:
  '@prisma/engines': true
  esbuild: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver
